# ============================================================
# METADATA
# ============================================================
name: rave_pipeline_class_guide
description: "AI Assistant Workflows for RAVE MCP Tools - Comprehensive guide for using RAVE MCP tools to help users with neuroscience data analysis pipelines"
version: "1.0.0"
category: guide
tags:
  - neuroscience
  - data-analysis
  - pipelines
  - workflows

# ============================================================
# TOOLS
# ============================================================
mcp_tools: true

tool_guide:
  # Discovery
  - tool: "ravepipeline-mcp_list_rave_pipelines"
    category: discovery
    when: "User asks about available analyses or pipelines"
    notes: "Always start here - never assume pipeline names"

  - tool: "ravepipeline-mcp_load_rave_pipeline"
    category: discovery
    when: "After identifying a pipeline, before any other operations"
    notes: "Required before get_info, set_settings, or run"
    preconditions:
      - "Know the pipeline name from mcp_list_rave_pipelines"

  # Information
  - tool: "ravepipeline-mcp_get_current_rave_pipeline_info"
    category: info
    when: "Need parameter schema, validation rules, or pipeline details"
    notes: "Use this to discover required parameters before configuration"
    preconditions:
      - "Pipeline must be loaded"

  # Configuration
  - tool: "ravepipeline-mcp_set_current_rave_pipeline_settings"
    category: configuration
    when: "User provides parameter values or you need to configure analysis"
    notes: "Always validate against schema from get_info first"
    preconditions:
      - "Pipeline must be loaded"
      - "Parameters validated against schema"

  # Execution
  - tool: "ravepipeline-mcp_run_current_rave_pipeline"
    category: execution
    when: "User confirms they want to execute the analysis"
    dangerous: true
    requires_approval: true
    preconditions:
      - "Pipeline must be loaded"
      - "Settings must be configured"
      - "User must explicitly approve execution"

  # Monitoring
  - tool: "ravepipeline-mcp_get_current_rave_pipeline_progress"
    category: monitoring
    when: "After starting execution, to track progress"
    notes: "Poll every 5 seconds until status is 'completed'"
    preconditions:
      - "Pipeline execution has been started"

  # Results
  - tool: "ravepipeline-mcp_read_current_rave_pipeline_results"
    category: results
    when: "Pipeline execution completed successfully"
    notes: "Present results with interpretation, not raw data dumps"
    preconditions:
      - "Pipeline execution completed"

# ============================================================
# GUIDANCE
# ============================================================
overview: |
  RAVE (Reproducible Analysis and Visualization of iEEG) is primarily built 
  with R programming language. Please use R language for reference.
  
  The RAVE-MCP tools enable AI assistants to:
  - Discover and explore available analysis pipelines
  - Configure pipeline parameters
  - Execute analyses with proper validation
  - Monitor execution progress
  - Retrieve and visualize results

best_practices:
  - title: "Always Start with Discovery"
    do: |
      1. Call mcp_list_rave_pipelines() to find available options
      2. Load the relevant pipeline with mcp_load_rave_pipeline()
      3. Get parameter details with mcp_get_current_rave_pipeline_info()
      4. Present options to user with descriptions
    dont: "Immediately try to run with guessed pipeline names or parameters"

  - title: "Validate Before Executing"
    do: |
      1. Load pipeline and get parameter schema
      2. Validate all parameters against schema (types, ranges, enums)
      3. Confirm settings with user before execution
      4. Then execute
    dont: "Set parameters and run without checking schema or user confirmation"

  - title: "Monitor Long-Running Operations"
    do: |
      1. Start pipeline execution
      2. Poll mcp_get_current_rave_pipeline_progress every 5 seconds
      3. Report progress to user: "Processing: 45% complete..."
      4. Confirm completion: "Analysis finished successfully!"
    dont: "Start pipeline and assume it completed without checking"

  - title: "Provide Context with Results"
    do: |
      Present interpreted results:
      "Analysis complete! Here's what I found:
       - Power spectrum peak at 12 Hz (alpha band)
       - Mean power: 15.3 µV²/Hz
       Would you like me to visualize these results?"
    dont: "Return raw data dumps without interpretation"

  - title: "Handle Errors Gracefully"
    do: |
      Explain what went wrong and suggest fixes:
      "The analysis encountered an error: 'Invalid frequency range'
       The requested range (2-500 Hz) exceeds Nyquist frequency (500 Hz).
       Would you like me to rerun with 2-400 Hz instead?"
    dont: "Just say 'Error occurred' and stop"

  - title: "Required Approval Workflows"
    do: |
      For dangerous operations:
      1. Present action details: tool, purpose, parameters, expected outcomes
      2. Wait for explicit user confirmation - NEVER auto-approve
      3. Execute only after approval
      4. Confirm execution started
    dont: "Execute dangerous operations without explicit user consent"

  - title: "Parameter Validation Checklist"
    do: |
      Before setting parameters, validate:
      - Type validation: string, number, boolean, array
      - Enum validation: value in allowed list
      - Range validation: numeric bounds, string length
      - Required parameters: all present
      - Dependencies: conditional parameters valid
    dont: "Pass parameters without validation against schema"

warnings:
  - "Never execute dangerous operations without explicit user approval"
  - "Always validate parameters against schema before setting"
  - "Monitor long-running pipelines - don't assume completion"
  - "Handle errors gracefully with clear explanations and recovery suggestions"
  - "Start with discovery tools before assuming pipeline names or parameters"
  - "Provide context and interpretation with results, not just raw data"
  - "For dangerous: true operations, show WARNING and request double confirmation"

# ============================================================
# JOBS
# ============================================================
jobs:
  # Pattern 1: Discovery
  pipeline-discovery:
    name: "Pipeline Discovery"
    description: "Discover and explore available analysis pipelines"
    steps:
      - name: "List all pipelines"
        tool: "ravepipeline-mcp_list_rave_pipelines"
        description: "Get all available pipelines"

      - name: "Filter by relevance"
        action: "filter"
        description: "Parse results for pipelines matching user's needs (e.g., power, spectral, frequency)"

      - name: "Load for details"
        tool: "ravepipeline-mcp_load_rave_pipeline"
        description: "Load each relevant pipeline to inspect"
        loop:
          over: "relevant_pipelines"

      - name: "Get parameter info"
        tool: "ravepipeline-mcp_get_current_rave_pipeline_info"
        description: "Get details for each loaded pipeline"

      - name: "Present options"
        action: "present"
        description: "Present options to user with descriptions"

  # Pattern 2: Configure and Run
  configure-and-run:
    name: "Configure and Execute Pipeline"
    description: "Complete workflow from configuration to execution"
    steps:
      - name: "Load pipeline"
        tool: "ravepipeline-mcp_load_rave_pipeline"
        description: "Load the target pipeline"

      - name: "Get parameter schema"
        tool: "ravepipeline-mcp_get_current_rave_pipeline_info"
        description: "Get parameter schema and validation rules"

      - name: "Validate requirements"
        action: "validate"
        description: "Check all required parameters exist and are valid"
        validation:
          check: "All required parameters present and valid"
          on_fail: "error"

      - name: "Set parameters"
        tool: "ravepipeline-mcp_set_current_rave_pipeline_settings"
        description: "Configure pipeline with validated parameters"

      - name: "Confirm with user"
        action: "confirm"
        description: "Present settings and request user approval"
        requires_approval: true

      - name: "Execute pipeline"
        tool: "ravepipeline-mcp_run_current_rave_pipeline"
        description: "Run the analysis"
        dangerous: true
        requires_approval: true

      - name: "Monitor progress"
        tool: "ravepipeline-mcp_get_current_rave_pipeline_progress"
        description: "Poll until complete"
        loop:
          until: "status == 'completed'"
          interval: "5 seconds"

      - name: "Retrieve results"
        tool: "ravepipeline-mcp_read_current_rave_pipeline_results"
        description: "Get and present analysis results"

  # Pattern 3: Iterative Analysis
  iterative-analysis:
    name: "Iterative Parameter Exploration"
    description: "Try different parameters to find optimal settings"
    steps:
      - name: "Set parameters"
        tool: "ravepipeline-mcp_set_current_rave_pipeline_settings"
        loop:
          over: "parameter_sets"
          item: "params"

      - name: "Run analysis"
        tool: "ravepipeline-mcp_run_current_rave_pipeline"
        requires_approval: true

      - name: "Wait for completion"
        tool: "ravepipeline-mcp_get_current_rave_pipeline_progress"
        loop:
          until: "status == 'completed'"

      - name: "Get results"
        tool: "ravepipeline-mcp_read_current_rave_pipeline_results"

      - name: "Evaluate and compare"
        action: "evaluate"
        description: "Compare results across parameter sets"

  # Pattern 4: Results Visualization
  results-visualization:
    name: "Results Visualization"
    description: "Read and visualize analysis results"
    steps:
      - name: "Read result data"
        tool: "ravepipeline-mcp_read_current_rave_pipeline_results"
        with:
          target_names: ["plot_data", "statistics"]

      - name: "Present with interpretation"
        action: "present"
        description: "Present visualization with statistical interpretation"

  # Advanced: Multi-Pipeline Workflow
  multi-pipeline:
    name: "Multi-Pipeline Sequential Analysis"
    description: "Sequential pipeline execution: Preprocessing → Analysis → Visualization"
    steps:
      # Preprocessing Stage
      - name: "Load notch filter"
        tool: "ravepipeline-mcp_load_rave_pipeline"
        with:
          pipeline_name: "notch_filter"

      - name: "Configure filtering"
        tool: "ravepipeline-mcp_set_current_rave_pipeline_settings"
        with:
          settings_json: '{"line_frequencies": [60, 120, 180]}'
        description: "Configure line noise frequencies (60 Hz and harmonics)"

      - name: "Execute filtering"
        tool: "ravepipeline-mcp_run_current_rave_pipeline"
        requires_approval: true

      - name: "Verify clean data"
        tool: "ravepipeline-mcp_read_current_rave_pipeline_results"

      # Analysis Stage
      - name: "Load wavelet pipeline"
        tool: "ravepipeline-mcp_load_rave_pipeline"
        with:
          pipeline_name: "wavelet_module"

      - name: "Configure time-frequency analysis"
        tool: "ravepipeline-mcp_set_current_rave_pipeline_settings"
        description: "Configure using filtered data from previous stage"

      - name: "Execute wavelet analysis"
        tool: "ravepipeline-mcp_run_current_rave_pipeline"
        requires_approval: true

      # Visualization Stage
      - name: "Read wavelet results"
        tool: "ravepipeline-mcp_read_current_rave_pipeline_results"

      - name: "Generate visualizations"
        action: "present"
        description: "Generate spectrograms and summary plots"

  # Advanced: Batch Processing
  batch-processing:
    name: "Batch Subject Processing"
    description: "Analyze multiple subjects with the same pipeline"
    strategy:
      parallel: true
      max_concurrent: 4
    steps:
      - name: "Load pipeline per subject"
        tool: "ravepipeline-mcp_load_rave_pipeline"
        loop:
          over: "subjects"
          item: "subject_id"

      - name: "Configure subject settings"
        tool: "ravepipeline-mcp_set_current_rave_pipeline_settings"
        description: "Configure subject-specific settings"

      - name: "Start async execution"
        tool: "ravepipeline-mcp_run_current_rave_pipeline"
        with:
          as_promise: true
        dangerous: true
        requires_approval: true

      - name: "Monitor all jobs"
        tool: "ravepipeline-mcp_get_current_rave_pipeline_progress"
        loop:
          until: "all_complete"
          interval: "10 seconds"

      - name: "Collect results"
        tool: "ravepipeline-mcp_read_current_rave_pipeline_results"
        loop:
          over: "subjects"

      - name: "Generate group statistics"
        action: "aggregate"
        description: "Generate group-level statistics and comparisons"

  # Error Recovery
  error-recovery:
    name: "Error Recovery"
    description: "Handle and recover from pipeline execution errors"
    if: "execution_failed"
    steps:
      - name: "Check error status"
        tool: "ravepipeline-mcp_get_current_rave_pipeline_progress"
        description: "Get current status and error messages"

      - name: "Parse error type"
        action: "parse_error"
        description: "Identify issue: missing data, invalid parameter, resource issue"

      - name: "Review constraints"
        tool: "ravepipeline-mcp_get_current_rave_pipeline_info"
        description: "Review parameter constraints and valid ranges"

      - name: "Suggest corrections"
        action: "suggest"
        description: "Suggest corrections based on schema and error"

      - name: "Apply corrections"
        tool: "ravepipeline-mcp_set_current_rave_pipeline_settings"
        description: "Apply corrected parameters"

      - name: "Retry execution"
        tool: "ravepipeline-mcp_run_current_rave_pipeline"
        requires_approval: true

# ============================================================
# EXAMPLES
# ============================================================
examples:
  - trigger: "I need to analyze gamma power in my iEEG data"
    flow:
      - tool: "ravepipeline-mcp_list_rave_pipelines"
        says: "Let me check what gamma analysis pipelines are available..."

      - action: "filter_and_present"
        says: "I found the power_explorer pipeline which can analyze gamma frequencies. Let me load it and see what parameters we need."

      - tool: "ravepipeline-mcp_load_rave_pipeline"
        with:
          pipeline_name: "power_explorer"

      - tool: "ravepipeline-mcp_get_current_rave_pipeline_info"
        says: "To analyze gamma power (30-100 Hz), I'll need to configure: frequency range, electrodes, and time windows. What electrodes would you like to analyze?"

  - trigger: "What analysis pipelines are available for power spectral analysis?"
    flow:
      - tool: "ravepipeline-mcp_list_rave_pipelines"
        says: "Let me find available power analysis pipelines..."

      - action: "filter_and_present"
        says: |
          I found 3 pipelines for power spectral analysis:
          
          1. **power_explorer** - Interactive power spectral density visualization
          2. **wavelet_module** - Time-frequency analysis using wavelet transforms
          3. **coherence_analysis** - Cross-spectral coherence between channels
          
          Would you like details on any of these?

  - trigger: "Run power analysis on my data with 2-150 Hz frequency range"
    flow:
      - tool: "ravepipeline-mcp_load_rave_pipeline"
        with:
          pipeline_name: "power_explorer"
        says: "Loading the power_explorer pipeline..."

      - tool: "ravepipeline-mcp_get_current_rave_pipeline_info"
        says: "Let me verify the frequency range parameters..."

      - tool: "ravepipeline-mcp_set_current_rave_pipeline_settings"
        with:
          settings_json: '{"freq_min": 2, "freq_max": 150}'
        says: "I'll configure the frequency range to 2-150 Hz. Ready to execute?"

      - action: "await_approval"
        says: "This will run the analysis. Do you want to proceed?"

      - tool: "ravepipeline-mcp_run_current_rave_pipeline"
        says: "Starting analysis..."

      - tool: "ravepipeline-mcp_get_current_rave_pipeline_progress"
        says: "Processing: 45% complete..."

      - tool: "ravepipeline-mcp_read_current_rave_pipeline_results"
        says: "Analysis complete! Here are the power spectrum results..."

# ============================================================
# SETTINGS
# ============================================================
settings:
  dangerous: false
  requires_approval: false
  estimated_duration: "N/A - this is a guide document"
